import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Link from "next/link";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Upload File",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <div className="flex gap-5 bg-sky-100 rounded-lg px-2 my-1">
          <Link
            href="/form_upload"
            className="px-1 rounded hover:bg-violet-600 active:bg-violet-700 focus:outline-none focus:ring focus:ring-violet-300 "
          >
            Form Upload
          </Link>
          <Link
            href="/api_upload"
            className="px-1 rounded hover:bg-violet-600 active:bg-violet-700 focus:outline-none focus:ring focus:ring-violet-300 "
          >
            Api Upload
          </Link>
        </div>

        {children}
      </body>
    </html>
  );
}
